name: Python CI
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
  workflow_dispatch:
  
jobs:
  coffeeShopSimulatorActions:
    runs-on: ubuntu-latest
    
    steps:    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Show Python version
      run: "python --version"
      
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Show directory
      run: 'pwd'
      
    - name: List files
      run: 'ls -al'
      
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run:
        python -m unittest ./coffee_shop_simulator_tests.py

  update-code:
    needs: coffeeShopSimulatorActions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.TOKEN }}
    
    - name: Set up Git user
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"


    - name: Commit changes
      run: |
        git add .
        git commit -m "Update the code" || echo "No changes"
        git remote set-url origin https://${{ secrets.TOKEN }}@github.com/Tonnnya/coffeeShopSimulator.git
        git push origin HEAD

  share-screenshot:
    needs: update-code
    runs-on: ubuntu-latest
    steps:
    - name: Upload screen
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: screenshots/screenshot.png  
