name: Python CI
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
  workflow_dispatch:
  
jobs:
  coffeeShopSimulatorActions:
    runs-on: ubuntu-latest
    
    steps:    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Show Python version
      run: "python --version"
      
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Show directory
      run: 'pwd'
      
    - name: List files
      run: 'ls -al'
      
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run:
        python -m unittest ./coffee_shop_simulator_tests.py

  update-code:
    needs: test_suck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Commit changes
      run: |
        git checkout -b update-code
        echo "New changes" > new_file.txt
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Update project code"
        git push origin update-code

    - name: Create pull request
      uses: peter-evans/create-pull-request@v5
      with:
        title: "Update project code"
        body: "This PR updates the project code with new changes."
        branch: update-code  # Гілка, з якої створюється PR
        base: main  # Гілка, в яку відкривається PR

  share-screenshot:
    needs: update-code  # Запустити цей job лише після створення PR
    runs-on: ubuntu-latest
    steps:
    - name: Upload screenshot
      uses: actions/upload-artifact@v3
      with:
        name: screenshot
        path: screenshot.png  # Шлях до скріншоту (замініть на реальний шлях)
